CREATE TABLE fatality(\n",
    "    FAT_YEARMONTH int,\n",
    "    FAT_DAY int,\n",
    "    FAT_TIME int,\n",
    "    FATALITY_ID int,\n",
    "    EVENT_ID int,\n",
    "    FATALITY_TYPE varchar(255),\n",
    "    FATALITY_DATE datetime,\n",
    "    FATALITY_AGE int,\n",
    "    FATALITY_SEX varchar(255),\n",
    "    FATALITY_LOCATION varchar(255), \n",
    "    EVENT_YEARMONTH int)